---
title: "Assignment2-607"
author: "Sangeetha Sasikumar"
date: "9/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMySQL)
library(ggplot2)

conn <- dbConnect(MySQL(), user='root', password='********', dbname='mydb', host='localhost')

dbListTables(conn)
```


```{r}
dbListTables(conn)
dbListFields(conn, 'movie_rating')
```



```{r, echo=FALSE}
#rs = dbSendQuery(mydb, "select * from movie_rating;")

df = dbGetQuery(conn, "SELECT * from movie_rating;")

print(df)
```
```{r}
summary(df)

```
```{r}
ggplot(df, aes(x=gender, y=spiderman)) + geom_bar(stat="identity") + 
  labs(x="gender", y="spiderman") +ggtitle("Ratings of Spiderman based on Gender")

```

This graph did not produce any good readable results, I will need to study data manipulation further to see if I can make something better. Also, I need to collect data in better formats next time. 
However, this was a really good assignment to learn to load sql data into R, and thats where more of
my time was spent.